<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-RDR3QR6H" failures="0" tests="1" name="Default test" time="3.075" errors="0" timestamp="2022-09-21T13:06:06 IST">
  <testcase classname="base.BaseClass" name="@BeforeTest launchBrowser" time="3.022">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.log4j.Logger.info(Object)&amp;quot; because &amp;quot;utils.Log.Log&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.log4j.Logger.info(Object)" because "utils.Log.Log" is null
at utils.Log.info(Log.java:47)
at base.BaseClass.launchBrowser(BaseClass.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:643)
at org.testng.TestRunner.beforeRun(TestRunner.java:632)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest launchBrowser -->
  <testcase classname="testcases.LoginValidCred" name="@BeforeClass createPOMObject" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeClass createPOMObject -->
  <testcase classname="base.BaseClass" name="@AfterTest flushExtent" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterTest flushExtent -->
  <testcase classname="testcases.LoginValidCred" name="loginWithValidCredentails" time="0.0">
    <skipped/>
  </testcase> <!-- loginWithValidCredentails -->
</testsuite> <!-- Default test -->
